name: Django CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      image: postgres
      env:
        POSTGRES_DB: postgres
        POSTGRES_USER: user
        POSTGRES_PASSWORD: password
        ports:
        - "5432:5432"
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5


      steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Tests
        run: |
          python ./manage.py test main.tests
